/**
 * MFASetup — manage TOTP two-factor authentication from the user settings / profile page.
 *
 * Usage:
 *   <MFASetup mfaEnabled={user.mfa_required} onSuccess={() => refetch()} />
 */

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useMFASetup, useMFAVerifySetup, useMFADisable, useGenerateBackupCodes } from '../../api/auth'
import { Button, Input } from '../../components/ui'

interface Props {
  mfaEnabled: boolean
  onSuccess?: () => void
}

const codeSchema = z.object({ code: z.string().min(6).max(8) })
type CodeFormData = z.infer<typeof codeSchema>

type Step = 'idle' | 'setup-qr' | 'setup-verify' | 'backup-codes' | 'disable'

export default function MFASetup({ mfaEnabled, onSuccess }: Props) {
  const [step, setStep] = useState<Step>('idle')
  const [totpUri, setTotpUri] = useState<string>('')
  const [secret, setSecret] = useState<string>('')
  const [backupCodes, setBackupCodes] = useState<string[]>([])

  const setupMutation = useMFASetup()
  const verifySetupMutation = useMFAVerifySetup()
  const disableMutation = useMFADisable()
  const backupCodesMutation = useGenerateBackupCodes()

  const setupForm = useForm<CodeFormData>({ resolver: zodResolver(codeSchema) })
  const disableForm = useForm<CodeFormData>({ resolver: zodResolver(codeSchema) })
  const backupForm = useForm<CodeFormData>({ resolver: zodResolver(codeSchema) })

  const handleStartSetup = async () => {
    try {
      const data = await setupMutation.mutateAsync(undefined)
      setTotpUri(data.totp_uri)
      setSecret(data.secret)
      setStep('setup-qr')
    } catch {
      /* error shown inline */
    }
  }

  const handleVerifySetup = async (data: CodeFormData) => {
    try {
      await verifySetupMutation.mutateAsync(data.code)
      setStep('idle')
      onSuccess?.()
    } catch (err: unknown) {
      const detail = (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      setupForm.setError('code', { message: detail || 'Invalid code. Please try again.' })
    }
  }

  const handleDisable = async (data: CodeFormData) => {
    try {
      await disableMutation.mutateAsync(data.code)
      setStep('idle')
      onSuccess?.()
    } catch (err: unknown) {
      const detail = (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      disableForm.setError('code', { message: detail || 'Invalid code. Please try again.' })
    }
  }

  const handleGenerateBackupCodes = async (data: CodeFormData) => {
    try {
      const result = await backupCodesMutation.mutateAsync(data.code)
      setBackupCodes(result.backup_codes)
    } catch (err: unknown) {
      const detail = (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      backupForm.setError('code', { message: detail || 'Invalid code. Please try again.' })
    }
  }

  // ── QR setup screen ───────────────────────────────────────────────────────
  if (step === 'setup-qr') {
    return (
      <div className="space-y-4 max-w-sm">
        <div>
          <h3 className="font-semibold text-gray-900 dark:text-gray-100">Scan QR code</h3>
          <p className="text-sm text-gray-500 mt-1">
            Open your authenticator app (Google Authenticator, Authy, etc.) and scan this code.
          </p>
        </div>

        {/* QR code — rendered via img tag pointing to a data URL generated by the backend */}
        <div className="flex justify-center">
          <img
            src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(totpUri)}`}
            alt="TOTP QR code"
            className="rounded-lg border border-gray-200 p-2"
            width={200}
            height={200}
          />
        </div>

        <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-3">
          <p className="text-xs text-gray-500 mb-1">Manual entry key</p>
          <code className="text-sm font-mono text-gray-800 dark:text-gray-200 break-all">{secret}</code>
        </div>

        <Button variant="primary" className="w-full" onClick={() => setStep('setup-verify')}>
          I've scanned the code
        </Button>
        <Button variant="ghost" className="w-full" onClick={() => setStep('idle')}>
          Cancel
        </Button>
      </div>
    )
  }

  // ── Verify setup screen ───────────────────────────────────────────────────
  if (step === 'setup-verify') {
    return (
      <form onSubmit={setupForm.handleSubmit(handleVerifySetup)} className="space-y-4 max-w-sm">
        <div>
          <h3 className="font-semibold text-gray-900 dark:text-gray-100">Verify authenticator</h3>
          <p className="text-sm text-gray-500 mt-1">
            Enter the 6-digit code from your authenticator app to confirm setup.
          </p>
        </div>

        <Input
          label="Verification code"
          type="text"
          inputMode="numeric"
          autoComplete="one-time-code"
          maxLength={8}
          autoFocus
          placeholder="000000"
          error={setupForm.formState.errors.code?.message}
          {...setupForm.register('code')}
        />

        <Button type="submit" variant="primary" className="w-full" loading={verifySetupMutation.isPending}>
          Enable 2FA
        </Button>
        <Button type="button" variant="ghost" className="w-full" onClick={() => setStep('setup-qr')}>
          Back
        </Button>
      </form>
    )
  }

  // ── Disable screen ────────────────────────────────────────────────────────
  if (step === 'disable') {
    return (
      <form onSubmit={disableForm.handleSubmit(handleDisable)} className="space-y-4 max-w-sm">
        <div>
          <h3 className="font-semibold text-gray-900 dark:text-gray-100">Disable 2FA</h3>
          <p className="text-sm text-gray-500 mt-1">
            Enter your current authenticator code to confirm disabling two-factor authentication.
          </p>
        </div>

        <div className="bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-sm text-amber-800">
          Your account will be less secure without 2FA.
        </div>

        <Input
          label="Authenticator code"
          type="text"
          inputMode="numeric"
          autoComplete="one-time-code"
          maxLength={8}
          autoFocus
          placeholder="000000"
          error={disableForm.formState.errors.code?.message}
          {...disableForm.register('code')}
        />

        <Button type="submit" variant="danger" className="w-full" loading={disableMutation.isPending}>
          Disable 2FA
        </Button>
        <Button type="button" variant="ghost" className="w-full" onClick={() => setStep('idle')}>
          Cancel
        </Button>
      </form>
    )
  }

  // ── Backup codes screen ───────────────────────────────────────────────────
  if (step === 'backup-codes') {
    if (backupCodes.length > 0) {
      return (
        <div className="space-y-4 max-w-sm">
          <div>
            <h3 className="font-semibold text-gray-900 dark:text-gray-100">Backup codes</h3>
            <p className="text-sm text-gray-500 mt-1">
              Save these codes in a safe place. Each code can only be used once.
            </p>
          </div>

          <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 grid grid-cols-2 gap-2">
            {backupCodes.map((code) => (
              <code key={code} className="text-sm font-mono text-gray-800 dark:text-gray-200 text-center py-1">
                {code}
              </code>
            ))}
          </div>

          <Button
            variant="ghost"
            className="w-full"
            onClick={() => {
              navigator.clipboard.writeText(backupCodes.join('\n'))
            }}
          >
            Copy to clipboard
          </Button>

          <Button variant="primary" className="w-full" onClick={() => { setBackupCodes([]); setStep('idle') }}>
            Done
          </Button>
        </div>
      )
    }

    return (
      <form onSubmit={backupForm.handleSubmit(handleGenerateBackupCodes)} className="space-y-4 max-w-sm">
        <div>
          <h3 className="font-semibold text-gray-900 dark:text-gray-100">Generate backup codes</h3>
          <p className="text-sm text-gray-500 mt-1">
            Enter your authenticator code to generate 10 new backup codes. This will invalidate any previous codes.
          </p>
        </div>

        <Input
          label="Authenticator code"
          type="text"
          inputMode="numeric"
          autoComplete="one-time-code"
          maxLength={8}
          autoFocus
          placeholder="000000"
          error={backupForm.formState.errors.code?.message}
          {...backupForm.register('code')}
        />

        <Button type="submit" variant="primary" className="w-full" loading={backupCodesMutation.isPending}>
          Generate codes
        </Button>
        <Button type="button" variant="ghost" className="w-full" onClick={() => setStep('idle')}>
          Cancel
        </Button>
      </form>
    )
  }

  // ── Idle / status screen ──────────────────────────────────────────────────
  return (
    <div className="space-y-4">
      <div className="flex items-start gap-4 p-4 border border-gray-200 dark:border-gray-700 rounded-xl">
        <div className={`mt-0.5 flex-shrink-0 w-8 h-8 rounded-lg flex items-center justify-center ${mfaEnabled ? 'bg-success/10' : 'bg-gray-100 dark:bg-gray-800'}`}>
          {mfaEnabled ? (
            <svg className="h-4 w-4 text-success" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
          ) : (
            <svg className="h-4 w-4 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
            </svg>
          )}
        </div>
        <div className="flex-1 min-w-0">
          <p className="font-medium text-gray-900 dark:text-gray-100">
            Two-factor authentication
            {mfaEnabled && <span className="ml-2 text-xs font-normal text-success">Enabled</span>}
          </p>
          <p className="text-sm text-gray-500 mt-0.5">
            {mfaEnabled
              ? 'Your account is protected with an authenticator app.'
              : 'Add an extra layer of security to your account.'}
          </p>
        </div>
      </div>

      {mfaEnabled ? (
        <div className="flex gap-2">
          <Button variant="outline" onClick={() => setStep('backup-codes')}>
            Backup codes
          </Button>
          <Button variant="danger-outline" onClick={() => setStep('disable')}>
            Disable 2FA
          </Button>
        </div>
      ) : (
        <Button
          variant="primary"
          onClick={handleStartSetup}
          loading={setupMutation.isPending}
        >
          Set up two-factor authentication
        </Button>
      )}

      {setupMutation.isError && (
        <p className="text-sm text-danger">Failed to start setup. Please try again.</p>
      )}
    </div>
  )
}
