"""add_drive_templates_table

Revision ID: 2ddb016ecd56
Revises: 9abefd9cd4c0
Create Date: 2026-03-13 07:56:42.645007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # noqa: F401
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ddb016ecd56'
down_revision: Union[str, None] = '9abefd9cd4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_api_keys',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(length=200), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Allowed scopes: ["calendar:read","calendar:write","bookings:read","bookings:write"]'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_calendar_api_keys_user_id'), 'calendar_api_keys', ['user_id'], unique=False, if_not_exists=True)
    op.create_table('calendar_webhooks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('secret', sa.String(length=200), nullable=False),
    sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='Array of subscribed event types e.g. ["event.created", "event.updated"]'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_webhooks_user_id'), 'calendar_webhooks', ['user_id'], unique=False, if_not_exists=True)
    op.create_table('smart_folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('filter_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_field', sa.String(length=50), nullable=False),
    sa.Column('sort_direction', sa.String(length=4), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smart_folders_owner_id'), 'smart_folders', ['owner_id'], unique=False, if_not_exists=True)
    op.create_table('form_approval_workflows',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='List of {approver_id, role, step_index, label}'),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )
    op.create_table('form_automations',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False, comment='submitted | approved | rejected | scheduled'),
    sa.Column('trigger_conditions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='[{type: create_lead|send_email|create_invoice|assign_task|update_inventory, config: {}}]'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_automations_form_id'), 'form_automations', ['form_id'], unique=False, if_not_exists=True)
    op.create_table('form_consents',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('data_retention_days', sa.Integer(), nullable=True),
    sa.Column('privacy_policy_url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_id')
    )
    op.create_table('form_response_drafts',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('draft_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_response_drafts_form_id'), 'form_response_drafts', ['form_id'], unique=False, if_not_exists=True)
    op.create_table('form_schedules',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True, comment='RFC 5545 RRULE string'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recipients', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='List of email addresses or user IDs'),
    sa.Column('distribution_channel', sa.String(length=20), nullable=False, comment='email | in_app | both'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_schedules_form_id'), 'form_schedules', ['form_id'], unique=False, if_not_exists=True)
    op.create_table('form_translations',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False, comment='BCP-47 locale code e.g. en, fr, sw, ar'),
    sa.Column('translations', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='{field_id: {label: str, options: [str], description: str}}'),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_translations_form_id'), 'form_translations', ['form_id'], unique=False, if_not_exists=True)
    op.create_table('form_consent_records',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consented_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_consent_records_form_id'), 'form_consent_records', ['form_id'], unique=False, if_not_exists=True)
    op.create_table('form_quiz_results',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('pass_fail', sa.String(length=10), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('graded_by', sa.UUID(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_id')
    )
    op.create_index(op.f('ix_form_quiz_results_form_id'), 'form_quiz_results', ['form_id'], unique=False, if_not_exists=True)
    op.create_table('form_response_approvals',
    sa.Column('response_id', sa.UUID(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | approved | rejected'),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['response_id'], ['form_responses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_response_approvals_response_id'), 'form_response_approvals', ['response_id'], unique=False, if_not_exists=True)
    op.create_table('note_databases',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('notebook_id', sa.UUID(), nullable=True),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('icon', sa.String(length=20), nullable=True),
    sa.Column('cover_image_url', sa.String(length=1000), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notebook_id'], ['notebooks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_databases_notebook_id'), 'note_databases', ['notebook_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_note_databases_owner_id'), 'note_databases', ['owner_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_note_databases_page_id'), 'note_databases', ['page_id'], unique=False, if_not_exists=True)
    op.create_table('note_share_links',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permissions', sa.String(length=10), nullable=False, comment='view | edit | comment'),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_share_links_note_id'), 'note_share_links', ['note_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_note_share_links_token'), 'note_share_links', ['token'], unique=True, if_not_exists=True)
    op.create_table('note_database_properties',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=False, comment='text|number|select|multi_select|date|checkbox|url|email|phone|person|file|relation|rollup|formula|status|created_time|last_edited_time'),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False, comment='Column width in pixels for table view'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['note_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_database_properties_database_id'), 'note_database_properties', ['database_id'], unique=False, if_not_exists=True)
    op.create_table('note_database_rows',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=True),
    sa.Column('values', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['database_id'], ['note_databases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['notes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_database_rows_database_id'), 'note_database_rows', ['database_id'], unique=False, if_not_exists=True)
    op.create_table('note_database_views',
    sa.Column('database_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('view_type', sa.String(length=50), nullable=False, comment='table|kanban|calendar|gallery|list|timeline'),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='filters, sorts, group_by, visible_properties, etc.'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['note_databases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_database_views_database_id'), 'note_database_views', ['database_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_cart_items_cart_id'), 'ecom_cart_items', ['cart_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_carts_session_key'), 'ecom_carts', ['session_key'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_carts_store_id'), 'ecom_carts', ['store_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_customers_email'), 'ecom_customers', ['email'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_ecom_customers_store_id'), 'ecom_customers', ['store_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_order_lines_order_id'), 'ecom_order_lines', ['order_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_orders_customer_id'), 'ecom_orders', ['customer_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_orders_order_number'), 'ecom_orders', ['order_number'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_ecom_orders_store_id'), 'ecom_orders', ['store_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_products_slug'), 'ecom_products', ['slug'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_ecom_products_store_id'), 'ecom_products', ['store_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_shipping_addresses_customer_id'), 'ecom_shipping_addresses', ['customer_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_ecom_stores_slug'), 'ecom_stores', ['slug'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_file_ai_metadata_file_id'), 'file_ai_metadata', ['file_id'], unique=True, if_not_exists=True)
    op.create_unique_constraint(None, 'finance_fixed_assets', ['asset_code'])
    op.create_unique_constraint(None, 'finance_reconciliations', ['statement_id'])
    op.create_index(op.f('ix_handbook_articles_slug'), 'handbook_articles', ['slug'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_handbook_categories_slug'), 'handbook_categories', ['slug'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_licenses_license_key'), 'licenses', ['license_key'], unique=True, if_not_exists=True)
    op.create_index(op.f('ix_project_task_comments_author_id'), 'project_task_comments', ['author_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_project_task_comments_parent_id'), 'project_task_comments', ['parent_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_project_task_custom_field_values_field_id'), 'project_task_custom_field_values', ['field_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_project_task_relationships_source_task_id'), 'project_task_relationships', ['source_task_id'], unique=False, if_not_exists=True)
    op.create_index(op.f('ix_project_task_relationships_target_task_id'), 'project_task_relationships', ['target_task_id'], unique=False, if_not_exists=True)
    op.create_unique_constraint(None, 'sso_user_mappings', ['provider_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sso_user_mappings', type_='foreignkey')
    op.drop_constraint(None, 'sso_user_mappings', type_='foreignkey')
    op.create_foreign_key('sso_user_mappings_provider_id_fkey', 'sso_user_mappings', 'sso_providers', ['provider_id'], ['id'])
    op.create_foreign_key('sso_user_mappings_user_id_fkey', 'sso_user_mappings', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sso_user_mappings', type_='unique')
    op.create_index('ix_sso_mapping_provider_ext', 'sso_user_mappings', ['provider_id', 'external_id'], unique=True, if_not_exists=True)
    op.create_index('ix_sc_workflow_templates_trigger_event', 'sc_workflow_templates', ['trigger_event'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_workflow_steps_run_id', 'sc_workflow_steps', ['run_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_workflow_runs_template_id', 'sc_workflow_runs', ['template_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_workflow_runs_status', 'sc_workflow_runs', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_supply_plans_status', 'sc_supply_plans', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_supply_plans_sop_id', 'sc_supply_plans', ['sop_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_supply_plan_lines_plan_id', 'sc_supply_plan_lines', ['plan_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_supply_plan_lines_item_id', 'sc_supply_plan_lines', ['item_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_suppliers_code', 'sc_suppliers', ['code'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_supplier_risks_supplier_id', 'sc_supplier_risks', ['supplier_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_supplier_risks_severity', 'sc_supplier_risks', ['severity'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_stock_health_scores_item_id', 'sc_stock_health_scores', ['item_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_stock_health_scores_health_status', 'sc_stock_health_scores', ['health_status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_sop_plans_status', 'sc_sop_plans', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_sop_plans_period_start', 'sc_sop_plans', ['period_start'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_safety_stock_configs_item_id', 'sc_safety_stock_configs', ['item_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_rfx_responses_supplier_id', 'sc_rfx_responses', ['supplier_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_rfx_responses_rfx_id', 'sc_rfx_responses', ['rfx_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_rfx_status', 'sc_rfx', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_rfx_rfx_type', 'sc_rfx', ['rfx_type'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_requisitions_status', 'sc_requisitions', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_replenishment_rules_warehouse_id', 'sc_replenishment_rules', ['warehouse_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_replenishment_rules_item_id', 'sc_replenishment_rules', ['item_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_kpis_period', 'sc_kpis', ['period'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_kpis_kpi_name', 'sc_kpis', ['kpi_name'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_grn_po', 'sc_goods_received_notes', ['purchase_order_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_forecast_scenarios_status', 'sc_forecast_scenarios', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_forecast_scenarios_created_by', 'sc_forecast_scenarios', ['created_by'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_events_occurred_at', 'sc_events', ['occurred_at'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_events_event_type', 'sc_events', ['event_type'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_esg_metrics_supplier_id', 'sc_esg_metrics', ['supplier_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_esg_metrics_period', 'sc_esg_metrics', ['period'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_esg_metrics_metric_type', 'sc_esg_metrics', ['metric_type'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_demand_signals_signal_type', 'sc_demand_signals', ['signal_type'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_demand_signals_item_id', 'sc_demand_signals', ['item_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_demand_forecasts_scenario_id', 'sc_demand_forecasts', ['scenario_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_demand_forecasts_item_id', 'sc_demand_forecasts', ['item_id'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_demand_forecasts_forecast_date', 'sc_demand_forecasts', ['forecast_date'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_control_tower_alerts_status', 'sc_control_tower_alerts', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_control_tower_alerts_severity', 'sc_control_tower_alerts', ['severity'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_control_tower_alerts_alert_type', 'sc_control_tower_alerts', ['alert_type'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_compliance_records_status', 'sc_compliance_records', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_compliance_records_entity_type', 'sc_compliance_records', ['entity_type'], unique=False, if_not_exists=True)
    op.create_index('ix_sc_capacity_plans_sop_id', 'sc_capacity_plans', ['sop_id'], unique=False, if_not_exists=True)
    op.add_column('project_task_relationships', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_task_relationships_created_by_fkey', 'project_task_relationships', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_project_task_relationships_target_task_id'), table_name='project_task_relationships')
    op.drop_index(op.f('ix_project_task_relationships_source_task_id'), table_name='project_task_relationships')
    op.create_unique_constraint('uq_task_relationship', 'project_task_relationships', ['source_task_id', 'target_task_id', 'relationship_type'])
    op.create_index('ix_project_task_relationships_target', 'project_task_relationships', ['target_task_id'], unique=False, if_not_exists=True)
    op.create_index('ix_project_task_relationships_source', 'project_task_relationships', ['source_task_id'], unique=False, if_not_exists=True)
    op.drop_index(op.f('ix_project_task_custom_field_values_field_id'), table_name='project_task_custom_field_values')
    op.add_column('project_task_comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_project_task_comments_parent_id'), table_name='project_task_comments')
    op.drop_index(op.f('ix_project_task_comments_author_id'), table_name='project_task_comments')
    op.add_column('project_task_checklists', sa.Column('is_done', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('project_task_checklists', sa.Column('due_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('project_task_checklists', sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_task_checklists', type_='foreignkey')
    op.create_foreign_key('project_task_checklists_assignee_id_fkey', 'project_task_checklists', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_project_task_audit_log_created_at', 'project_task_audit_log', ['created_at'], unique=False, if_not_exists=True)
    op.add_column('project_recurring_configs', sa.Column('estimated_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('project_recurring_configs', sa.Column('interval', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('project_recurring_configs', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('project_recurring_configs', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('project_recurring_configs', sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=False))
    op.add_column('project_recurring_configs', sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('project_recurring_configs', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR(length=100)), autoincrement=False, nullable=True))
    op.add_column('project_recurring_configs', sa.Column('assignee_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_recurring_configs', type_='foreignkey')
    op.create_foreign_key('project_recurring_configs_assignee_id_fkey', 'project_recurring_configs', 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('project_recurring_configs_created_by_fkey', 'project_recurring_configs', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('project_guest_access', sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'viewer'::character varying"), autoincrement=False, nullable=False))
    op.add_column('project_guest_access', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_guest_access', type_='foreignkey')
    op.create_foreign_key('project_guest_access_invited_by_fkey', 'project_guest_access', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.add_column('project_custom_fields', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_custom_fields_created_by_fkey', 'project_custom_fields', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('project_automation_rules', sa.Column('trigger', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('project_automation_rules', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_automation_rules', type_='foreignkey')
    op.create_foreign_key('project_automation_rules_created_by_fkey', 'project_automation_rules', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_pos_transactions_session', 'pos_transactions', ['session_id'], unique=False, if_not_exists=True)
    op.create_index('ix_pos_transactions_created_at', 'pos_transactions', ['created_at'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'pos_transaction_lines', type_='foreignkey')
    op.drop_constraint(None, 'pos_transaction_lines', type_='foreignkey')
    op.drop_constraint(None, 'pos_transaction_lines', type_='foreignkey')
    op.create_index('ix_pos_transaction_lines_txn', 'pos_transaction_lines', ['transaction_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'pos_sessions', type_='foreignkey')
    op.create_index('ix_pos_sessions_cashier_status', 'pos_sessions', ['cashier_id', 'status'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'pos_product_modifier_links', type_='foreignkey')
    op.drop_constraint(None, 'pos_product_modifier_links', type_='foreignkey')
    op.create_foreign_key('pos_product_modifier_links_item_id_fkey', 'pos_product_modifier_links', 'inventory_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('pos_product_modifier_links_modifier_group_id_fkey', 'pos_product_modifier_links', 'pos_modifier_groups', ['modifier_group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pos_pickup_orders', type_='foreignkey')
    op.drop_constraint(None, 'pos_pickup_orders', type_='foreignkey')
    op.create_index('ix_pos_payments_txn', 'pos_payments', ['transaction_id'], unique=False, if_not_exists=True)
    op.add_column('pos_payment_gateway_configs', sa.Column('gateway_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('pos_payment_gateway_configs', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pos_payment_gateway_configs', type_='foreignkey')
    op.drop_constraint(None, 'pos_modifiers', type_='foreignkey')
    op.create_foreign_key('pos_modifiers_group_id_fkey', 'pos_modifiers', 'pos_modifier_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'pos_gift_cards', type_='foreignkey')
    op.create_foreign_key('fk_pos_gift_cards_issued_by', 'pos_gift_cards', 'users', ['issued_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'pos_bundle_items', type_='foreignkey')
    op.create_foreign_key('pos_bundle_items_bundle_id_fkey', 'pos_bundle_items', 'pos_bundles', ['bundle_id'], ['id'], ondelete='CASCADE')
    op.add_column('note_audit_logs', sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mfg_work_orders', type_='foreignkey')
    op.create_index('ix_mfg_wo_status', 'mfg_work_orders', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_mfg_wo_bom', 'mfg_work_orders', ['bom_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'mfg_maintenance_schedules', type_='foreignkey')
    op.create_index('ix_meeting_links_meeting_type', 'meeting_links', ['meeting_id', 'link_type'], unique=False, if_not_exists=True)
    op.create_index('ix_mailbox_messages_priority_score', 'mailbox_messages', ['priority_score'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'loyalty_tiers', type_='foreignkey')
    op.create_foreign_key('loyalty_tiers_program_id_fkey', 'loyalty_tiers', 'loyalty_programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'loyalty_rewards', type_='foreignkey')
    op.create_foreign_key('loyalty_rewards_program_id_fkey', 'loyalty_rewards', 'loyalty_programs', ['program_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_licenses_license_key'), table_name='licenses')
    op.create_unique_constraint('licenses_license_key_key', 'licenses', ['license_key'])
    op.drop_constraint(None, 'kds_order_items', type_='foreignkey')
    op.drop_constraint(None, 'kds_order_items', type_='foreignkey')
    op.create_foreign_key('kds_order_items_kds_order_id_fkey', 'kds_order_items', 'kds_orders', ['kds_order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'hr_workforce_scenarios', type_='foreignkey')
    op.drop_constraint(None, 'hr_workforce_scenarios', type_='foreignkey')
    op.create_foreign_key('hr_workforce_scenarios_approved_by_fkey', 'hr_workforce_scenarios', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_workforce_scenarios_created_by_fkey', 'hr_workforce_scenarios', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_hr_workforce_scenarios_is_approved', 'hr_workforce_scenarios', ['is_approved'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workforce_scenarios_fiscal_year', 'hr_workforce_scenarios', ['fiscal_year'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workforce_scenarios_created_by', 'hr_workforce_scenarios', ['created_by'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_workflows', type_='foreignkey')
    op.create_foreign_key('hr_workflows_created_by_fkey', 'hr_workflows', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_hr_workflows_trigger_type', 'hr_workflows', ['trigger_type'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workflows_is_active', 'hr_workflows', ['is_active'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workflows_category', 'hr_workflows', ['category'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_workflow_executions', type_='foreignkey')
    op.drop_constraint(None, 'hr_workflow_executions', type_='foreignkey')
    op.create_foreign_key('hr_workflow_executions_triggered_by_fkey', 'hr_workflow_executions', 'users', ['triggered_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_workflow_executions_workflow_id_fkey', 'hr_workflow_executions', 'hr_workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_workflow_executions_workflow_id', 'hr_workflow_executions', ['workflow_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workflow_executions_status', 'hr_workflow_executions', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workflow_executions_started_at', 'hr_workflow_executions', ['started_at'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_workflow_approvals', type_='foreignkey')
    op.drop_constraint(None, 'hr_workflow_approvals', type_='foreignkey')
    op.create_foreign_key('hr_workflow_approvals_execution_id_fkey', 'hr_workflow_approvals', 'hr_workflow_executions', ['execution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_workflow_approvals_approver_id_fkey', 'hr_workflow_approvals', 'users', ['approver_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hr_workflow_approvals_status', 'hr_workflow_approvals', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workflow_approvals_execution_id', 'hr_workflow_approvals', ['execution_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_workflow_approvals_approver_id', 'hr_workflow_approvals', ['approver_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_surveys', type_='foreignkey')
    op.create_foreign_key('hr_surveys_created_by_fkey', 'hr_surveys', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_hr_surveys_type', 'hr_surveys', ['survey_type'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_surveys_status', 'hr_surveys', ['status'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_survey_responses', type_='foreignkey')
    op.drop_constraint(None, 'hr_survey_responses', type_='foreignkey')
    op.create_foreign_key('hr_survey_responses_survey_id_fkey', 'hr_survey_responses', 'hr_surveys', ['survey_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_survey_responses_respondent_id_fkey', 'hr_survey_responses', 'hr_employees', ['respondent_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hr_survey_responses_survey_id', 'hr_survey_responses', ['survey_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_succession_plans_department_id', 'hr_succession_plans', ['department_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_skill_ontology', type_='foreignkey')
    op.create_foreign_key('fk_hr_skill_ontology_parent_id', 'hr_skill_ontology', 'hr_skill_ontology', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hr_skill_ontology_parent_id', 'hr_skill_ontology', ['parent_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_skill_ontology_category', 'hr_skill_ontology', ['category'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_shift_assignments', type_='foreignkey')
    op.create_foreign_key('hr_shift_assignments_employee_id_fkey', 'hr_shift_assignments', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_shift_assignments_employee_id', 'hr_shift_assignments', ['employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_shift_assignments_date', 'hr_shift_assignments', ['assignment_date'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_review_assignments', type_='foreignkey')
    op.drop_constraint(None, 'hr_review_assignments', type_='foreignkey')
    op.drop_constraint(None, 'hr_review_assignments', type_='foreignkey')
    op.create_foreign_key('hr_review_assignments_cycle_id_fkey', 'hr_review_assignments', 'hr_review_cycles', ['cycle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_review_assignments_reviewee_id_fkey', 'hr_review_assignments', 'hr_employees', ['reviewee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_review_assignments_reviewer_id_fkey', 'hr_review_assignments', 'hr_employees', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_review_assignments_reviewer_id', 'hr_review_assignments', ['reviewer_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_review_assignments_reviewee_id', 'hr_review_assignments', ['reviewee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_review_assignments_cycle_id', 'hr_review_assignments', ['cycle_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_recognitions', type_='foreignkey')
    op.drop_constraint(None, 'hr_recognitions', type_='foreignkey')
    op.drop_constraint(None, 'hr_recognitions', type_='foreignkey')
    op.create_foreign_key('hr_recognitions_to_employee_id_fkey', 'hr_recognitions', 'hr_employees', ['to_employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_recognitions_from_employee_id_fkey', 'hr_recognitions', 'hr_employees', ['from_employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_recognitions_department_id_fkey', 'hr_recognitions', 'hr_departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hr_recognitions_type', 'hr_recognitions', ['recognition_type'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_recognitions_to_employee_id', 'hr_recognitions', ['to_employee_id'], unique=False, if_not_exists=True)
    op.add_column('hr_payslips', sa.Column('pay_run_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('hr_payslips_pay_run_id_fkey', 'hr_payslips', 'hr_pay_runs', ['pay_run_id'], ['id'])
    op.drop_constraint(None, 'hr_onboarding_templates', type_='foreignkey')
    op.drop_constraint(None, 'hr_onboarding_templates', type_='foreignkey')
    op.create_foreign_key('hr_onboarding_templates_department_id_fkey', 'hr_onboarding_templates', 'hr_departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_onboarding_templates_created_by_fkey', 'hr_onboarding_templates', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'hr_onboarding_tasks', type_='foreignkey')
    op.drop_constraint(None, 'hr_onboarding_tasks', type_='foreignkey')
    op.drop_constraint(None, 'hr_onboarding_tasks', type_='foreignkey')
    op.create_foreign_key('hr_onboarding_tasks_assigned_to_fkey', 'hr_onboarding_tasks', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_onboarding_tasks_template_id_fkey', 'hr_onboarding_tasks', 'hr_onboarding_templates', ['template_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_onboarding_tasks_employee_id_fkey', 'hr_onboarding_tasks', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_onboarding_tasks_status', 'hr_onboarding_tasks', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_onboarding_tasks_employee_id', 'hr_onboarding_tasks', ['employee_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_merit_increases', type_='foreignkey')
    op.create_foreign_key('hr_merit_increases_employee_id_fkey', 'hr_merit_increases', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_merit_increases_employee_id', 'hr_merit_increases', ['employee_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_job_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'hr_job_requisitions', type_='foreignkey')
    op.drop_constraint(None, 'hr_job_requisitions', type_='foreignkey')
    op.create_foreign_key('hr_job_requisitions_hiring_manager_id_fkey', 'hr_job_requisitions', 'users', ['hiring_manager_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_job_requisitions_department_id_fkey', 'hr_job_requisitions', 'hr_departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_job_requisitions_created_by_fkey', 'hr_job_requisitions', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_hr_job_requisitions_status', 'hr_job_requisitions', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_job_requisitions_department_id', 'hr_job_requisitions', ['department_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_interviews', type_='foreignkey')
    op.create_foreign_key('hr_interviews_application_id_fkey', 'hr_interviews', 'hr_candidate_applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_interviews_scheduled_at', 'hr_interviews', ['scheduled_at'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_interviews_application_id', 'hr_interviews', ['application_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_goals_owner_id', 'hr_goals', ['owner_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_goal_updates', type_='foreignkey')
    op.create_foreign_key('hr_goal_updates_goal_id_fkey', 'hr_goal_updates', 'hr_goals', ['goal_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_goal_updates_goal_id', 'hr_goal_updates', ['goal_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_flight_risk_scores', type_='foreignkey')
    op.create_foreign_key('hr_flight_risk_scores_employee_id_fkey', 'hr_flight_risk_scores', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_flight_risk_scores_risk_level', 'hr_flight_risk_scores', ['risk_level'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_flight_risk_scores_employee_id', 'hr_flight_risk_scores', ['employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_flight_risk_scores_calculated_at', 'hr_flight_risk_scores', ['calculated_at'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_equity_grants', type_='foreignkey')
    op.create_foreign_key('hr_equity_grants_employee_id_fkey', 'hr_equity_grants', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_equity_grants_employee_id', 'hr_equity_grants', ['employee_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_employee_skills', type_='foreignkey')
    op.create_foreign_key('hr_employee_skills_employee_id_fkey', 'hr_employee_skills', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_employee_skills_employee_id', 'hr_employee_skills', ['employee_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_employee_activity_log', type_='foreignkey')
    op.create_foreign_key('hr_employee_activity_log_employee_id_fkey', 'hr_employee_activity_log', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_employee_activity_log_occurred', 'hr_employee_activity_log', ['occurred_at'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_employee_activity_log_employee_id', 'hr_employee_activity_log', ['employee_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_document_versions', type_='foreignkey')
    op.create_foreign_key('hr_document_versions_document_id_fkey', 'hr_document_versions', 'hr_employee_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_document_versions_document_id', 'hr_document_versions', ['document_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_courses', type_='foreignkey')
    op.create_foreign_key('hr_courses_created_by_fkey', 'hr_courses', 'users', ['created_by'], ['id'], ondelete='RESTRICT')
    op.create_index('ix_hr_courses_is_published', 'hr_courses', ['is_published'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_courses_category', 'hr_courses', ['category'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_course_modules', type_='foreignkey')
    op.create_foreign_key('hr_course_modules_course_id_fkey', 'hr_course_modules', 'hr_courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_course_modules_course_id', 'hr_course_modules', ['course_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_course_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'hr_course_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'hr_course_enrollments', type_='foreignkey')
    op.create_foreign_key('hr_course_enrollments_course_id_fkey', 'hr_course_enrollments', 'hr_courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_course_enrollments_employee_id_fkey', 'hr_course_enrollments', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_course_enrollments_enrolled_by_fkey', 'hr_course_enrollments', 'users', ['enrolled_by'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hr_course_enrollments_status', 'hr_course_enrollments', ['status'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_course_enrollments_employee_id', 'hr_course_enrollments', ['employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_course_enrollments_course_id', 'hr_course_enrollments', ['course_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_continuous_feedback', type_='foreignkey')
    op.drop_constraint(None, 'hr_continuous_feedback', type_='foreignkey')
    op.create_foreign_key('hr_continuous_feedback_from_employee_id_fkey', 'hr_continuous_feedback', 'hr_employees', ['from_employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_continuous_feedback_to_employee_id_fkey', 'hr_continuous_feedback', 'hr_employees', ['to_employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_continuous_feedback_to_employee_id', 'hr_continuous_feedback', ['to_employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_continuous_feedback_from_employee_id', 'hr_continuous_feedback', ['from_employee_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_certifications', type_='foreignkey')
    op.drop_constraint(None, 'hr_certifications', type_='foreignkey')
    op.drop_constraint(None, 'hr_certifications', type_='foreignkey')
    op.create_foreign_key('hr_certifications_course_id_fkey', 'hr_certifications', 'hr_courses', ['course_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_certifications_verified_by_fkey', 'hr_certifications', 'users', ['verified_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('hr_certifications_employee_id_fkey', 'hr_certifications', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_certifications_expiry_date', 'hr_certifications', ['expiry_date'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_certifications_employee_id', 'hr_certifications', ['employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_candidates_email', 'hr_candidates', ['email'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_candidate_applications', type_='foreignkey')
    op.drop_constraint(None, 'hr_candidate_applications', type_='foreignkey')
    op.drop_constraint(None, 'hr_candidate_applications', type_='foreignkey')
    op.create_foreign_key('hr_candidate_applications_candidate_id_fkey', 'hr_candidate_applications', 'hr_candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_candidate_applications_requisition_id_fkey', 'hr_candidate_applications', 'hr_job_requisitions', ['requisition_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_candidate_applications_assigned_to_fkey', 'hr_candidate_applications', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_index('ix_hr_candidate_applications_stage', 'hr_candidate_applications', ['stage'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_candidate_applications_requisition_id', 'hr_candidate_applications', ['requisition_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_candidate_applications_candidate_id', 'hr_candidate_applications', ['candidate_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_burnout_indicators', type_='foreignkey')
    op.create_foreign_key('hr_burnout_indicators_employee_id_fkey', 'hr_burnout_indicators', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_burnout_indicators_risk_level', 'hr_burnout_indicators', ['risk_level'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_burnout_indicators_employee_id', 'hr_burnout_indicators', ['employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_burnout_indicators_calculated_at', 'hr_burnout_indicators', ['calculated_at'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_buddy_assignments', type_='foreignkey')
    op.drop_constraint(None, 'hr_buddy_assignments', type_='foreignkey')
    op.create_foreign_key('hr_buddy_assignments_new_employee_id_fkey', 'hr_buddy_assignments', 'hr_employees', ['new_employee_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('hr_buddy_assignments_buddy_employee_id_fkey', 'hr_buddy_assignments', 'hr_employees', ['buddy_employee_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'hr_bonuses', type_='foreignkey')
    op.create_foreign_key('hr_bonuses_employee_id_fkey', 'hr_bonuses', 'hr_employees', ['employee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_bonuses_employee_id', 'hr_bonuses', ['employee_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_audit_field_changes_table_name', 'hr_audit_field_changes', ['table_name'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_audit_field_changes_record_id', 'hr_audit_field_changes', ['record_id'], unique=False, if_not_exists=True)
    op.drop_constraint(None, 'hr_analytics_dashboards', type_='foreignkey')
    op.create_foreign_key('hr_analytics_dashboards_owner_id_fkey', 'hr_analytics_dashboards', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_hr_analytics_dashboards_owner_id', 'hr_analytics_dashboards', ['owner_id'], unique=False, if_not_exists=True)
    op.create_index('ix_hr_analytics_dashboards_is_shared', 'hr_analytics_dashboards', ['is_shared'], unique=False, if_not_exists=True)
    op.drop_index(op.f('ix_handbook_categories_slug'), table_name='handbook_categories')
    op.create_index('ix_handbook_categories_slug', 'handbook_categories', ['slug'], unique=False, if_not_exists=True)
    op.create_unique_constraint('handbook_categories_slug_key', 'handbook_categories', ['slug'])
    op.drop_index(op.f('ix_handbook_articles_slug'), table_name='handbook_articles')
    op.create_index('ix_handbook_articles_slug', 'handbook_articles', ['slug'], unique=False, if_not_exists=True)
    op.create_unique_constraint('handbook_articles_slug_key', 'handbook_articles', ['slug'])
    op.add_column('finance_vendor_bills', sa.Column('bill_type', sa.VARCHAR(length=20), server_default=sa.text("'expense'::character varying"), autoincrement=False, nullable=False))
    op.add_column('finance_recurring_invoices', sa.Column('invoice_type', sa.VARCHAR(length=20), server_default=sa.text("'sales'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'finance_reconciliations', type_='unique')
    op.add_column('finance_fixed_assets', sa.Column('disposed_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('finance_fixed_assets', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('finance_fixed_assets', sa.Column('asset_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('finance_fixed_assets', sa.Column('disposed_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'finance_fixed_assets', type_='unique')
    op.create_unique_constraint('finance_fixed_assets_asset_number_key', 'finance_fixed_assets', ['asset_number'])
    op.create_index('ix_finance_exchange_rates_date', 'finance_exchange_rates', ['from_currency_id', 'to_currency_id', 'effective_date'], unique=False, if_not_exists=True)
    op.add_column('finance_accounts', sa.Column('balance', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_file_ai_metadata_file_id'), table_name='file_ai_metadata')
    op.create_index('ix_file_ai_metadata_file_id', 'file_ai_metadata', ['file_id'], unique=False, if_not_exists=True)
    op.create_unique_constraint('file_ai_metadata_file_id_key', 'file_ai_metadata', ['file_id'])
    op.drop_index(op.f('ix_ecom_stores_slug'), table_name='ecom_stores')
    op.create_unique_constraint('ecom_stores_slug_key', 'ecom_stores', ['slug'])
    op.drop_constraint(None, 'ecom_shipping_addresses', type_='foreignkey')
    op.create_foreign_key('ecom_shipping_addresses_customer_id_fkey', 'ecom_shipping_addresses', 'ecom_customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_ecom_shipping_addresses_customer_id'), table_name='ecom_shipping_addresses')
    op.drop_constraint(None, 'ecom_products', type_='foreignkey')
    op.drop_constraint(None, 'ecom_products', type_='foreignkey')
    op.create_foreign_key('ecom_products_inventory_item_id_fkey', 'ecom_products', 'inventory_items', ['inventory_item_id'], ['id'])
    op.create_foreign_key('ecom_products_store_id_fkey', 'ecom_products', 'ecom_stores', ['store_id'], ['id'])
    op.drop_index(op.f('ix_ecom_products_store_id'), table_name='ecom_products')
    op.drop_index(op.f('ix_ecom_products_slug'), table_name='ecom_products')
    op.create_index('ix_ecom_products_store_slug', 'ecom_products', ['store_id', 'slug'], unique=True, if_not_exists=True)
    op.drop_constraint(None, 'ecom_orders', type_='foreignkey')
    op.drop_constraint(None, 'ecom_orders', type_='foreignkey')
    op.drop_constraint(None, 'ecom_orders', type_='foreignkey')
    op.create_foreign_key('ecom_orders_store_id_fkey', 'ecom_orders', 'ecom_stores', ['store_id'], ['id'])
    op.create_foreign_key('ecom_orders_shipping_address_id_fkey', 'ecom_orders', 'ecom_shipping_addresses', ['shipping_address_id'], ['id'])
    op.create_foreign_key('ecom_orders_customer_id_fkey', 'ecom_orders', 'ecom_customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_ecom_orders_store_id'), table_name='ecom_orders')
    op.drop_index(op.f('ix_ecom_orders_order_number'), table_name='ecom_orders')
    op.drop_index(op.f('ix_ecom_orders_customer_id'), table_name='ecom_orders')
    op.create_index('ix_ecom_orders_customer', 'ecom_orders', ['customer_id'], unique=False, if_not_exists=True)
    op.create_unique_constraint('ecom_orders_order_number_key', 'ecom_orders', ['order_number'])
    op.drop_constraint(None, 'ecom_order_lines', type_='foreignkey')
    op.drop_constraint(None, 'ecom_order_lines', type_='foreignkey')
    op.create_foreign_key('ecom_order_lines_order_id_fkey', 'ecom_order_lines', 'ecom_orders', ['order_id'], ['id'])
    op.create_foreign_key('ecom_order_lines_product_id_fkey', 'ecom_order_lines', 'ecom_products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_ecom_order_lines_order_id'), table_name='ecom_order_lines')
    op.drop_constraint(None, 'ecom_customers', type_='foreignkey')
    op.drop_constraint(None, 'ecom_customers', type_='foreignkey')
    op.create_foreign_key('ecom_customer_accounts_store_id_fkey', 'ecom_customers', 'ecom_stores', ['store_id'], ['id'])
    op.create_foreign_key('ecom_customer_accounts_crm_contact_id_fkey', 'ecom_customers', 'crm_contacts', ['crm_contact_id'], ['id'])
    op.drop_index(op.f('ix_ecom_customers_store_id'), table_name='ecom_customers')
    op.drop_index(op.f('ix_ecom_customers_email'), table_name='ecom_customers')
    op.create_index('ix_ecom_customers_store_email', 'ecom_customers', ['store_id', 'email'], unique=True, if_not_exists=True)
    op.drop_constraint(None, 'ecom_carts', type_='foreignkey')
    op.drop_constraint(None, 'ecom_carts', type_='foreignkey')
    op.create_foreign_key('ecom_carts_customer_id_fkey', 'ecom_carts', 'ecom_customers', ['customer_id'], ['id'])
    op.create_foreign_key('ecom_carts_store_id_fkey', 'ecom_carts', 'ecom_stores', ['store_id'], ['id'])
    op.drop_index(op.f('ix_ecom_carts_store_id'), table_name='ecom_carts')
    op.drop_index(op.f('ix_ecom_carts_session_key'), table_name='ecom_carts')
    op.drop_constraint(None, 'ecom_cart_items', type_='foreignkey')
    op.drop_constraint(None, 'ecom_cart_items', type_='foreignkey')
    op.create_foreign_key('ecom_cart_items_cart_id_fkey', 'ecom_cart_items', 'ecom_carts', ['cart_id'], ['id'])
    op.create_foreign_key('ecom_cart_items_product_id_fkey', 'ecom_cart_items', 'ecom_products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_ecom_cart_items_cart_id'), table_name='ecom_cart_items')
    op.add_column('drive_files', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('ix_drive_files_search_vector', 'drive_files', ['search_vector'], unique=False, postgresql_using='gin', if_not_exists=True)
    op.create_index('ix_drive_files_embedding_hnsw', 'drive_files', ['content_embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', if_not_exists=True)
    op.create_unique_constraint('uq_document_bookmarks_user_file', 'document_bookmarks', ['user_id', 'file_id'])
    op.add_column('crm_sequence_enrollments', sa.Column('current_step', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('crm_sequence_enrollments', sa.Column('next_action_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crm_sequence_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'crm_sequence_enrollments', type_='foreignkey')
    op.add_column('crm_sales_activities', sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crm_sales_activities', type_='foreignkey')
    op.drop_constraint(None, 'crm_sales_activities', type_='foreignkey')
    op.drop_constraint(None, 'crm_sales_activities', type_='foreignkey')
    op.drop_constraint(None, 'crm_sales_activities', type_='foreignkey')
    op.add_column('crm_lead_scoring_rules', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('crm_lead_scoring_rules', sa.Column('field', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'crm_lead_scoring_rules', type_='foreignkey')
    op.add_column('crm_duplicate_candidates', sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('crm_duplicate_candidates', sa.Column('match_reasons', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crm_duplicate_candidates', type_='foreignkey')
    op.add_column('crm_custom_field_definitions', sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crm_custom_field_definitions', type_='foreignkey')
    op.add_column('crm_contact_notes', sa.Column('subject', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'calendar_permissions', type_='foreignkey')
    op.drop_column('calendar_permissions', 'granted_by')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.add_column('agent_runs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('agent_run_steps', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('agent_approvals', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_table('calendar_drive_attachments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attached_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attached_by'], ['users.id'], name='calendar_drive_attachments_attached_by_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], name='calendar_drive_attachments_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['drive_files.id'], name='calendar_drive_attachments_file_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='calendar_drive_attachments_pkey')
    )
    op.create_index('ix_calendar_drive_attachments_event_id', 'calendar_drive_attachments', ['event_id'], unique=False, if_not_exists=True)
    op.create_table('drive_auto_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('suggested_by', sa.VARCHAR(length=20), server_default=sa.text("'''ai'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'''suggested'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('confirmed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name='drive_auto_links_confirmed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['drive_files.id'], name='drive_auto_links_file_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_auto_links_pkey')
    )
    op.create_index('ix_drive_auto_links_file_id', 'drive_auto_links', ['file_id'], unique=False, if_not_exists=True)
    op.create_table('drive_anomaly_alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), server_default=sa.text("'''medium'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_resolved', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name='drive_anomaly_alerts_resolved_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='drive_anomaly_alerts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_anomaly_alerts_pkey')
    )
    op.create_index('ix_drive_anomaly_alerts_user_id', 'drive_anomaly_alerts', ['user_id'], unique=False, if_not_exists=True)
    op.create_index('ix_drive_anomaly_alerts_detected_at', 'drive_anomaly_alerts', ['detected_at'], unique=False, if_not_exists=True)
    op.create_table('drive_content_types',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('required_fields', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('allowed_mime_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_system', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='drive_content_types_created_by_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_content_types_pkey'),
    sa.UniqueConstraint('name', name='drive_content_types_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('drive_contract_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expiry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('renewal_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('contract_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('key_obligations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('payment_terms', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('governing_law', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('termination_clauses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('auto_renews', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notice_period_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('renewal_alert_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('expiry_alert_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['drive_files.id'], name='drive_contract_metadata_file_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_contract_metadata_pkey'),
    sa.UniqueConstraint('file_id', name='drive_contract_metadata_file_id_key')
    )
    op.create_index('ix_drive_contract_metadata_file_id', 'drive_contract_metadata', ['file_id'], unique=False, if_not_exists=True)
    op.create_table('drive_content_type_folders',
    sa.Column('content_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('enforce_on_upload', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['drive_content_types.id'], name='drive_content_type_folders_content_type_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['drive_folders.id'], name='drive_content_type_folders_folder_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_type_id', 'folder_id', name='drive_content_type_folders_pkey')
    )
    op.create_table('drive_storage_tiers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(length=20), server_default=sa.text("'''hot'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('tiered_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tiered_by', sa.VARCHAR(length=20), server_default=sa.text("'''auto'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('restore_requested_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('restore_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['drive_files.id'], name='drive_storage_tiers_file_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_storage_tiers_pkey'),
    sa.UniqueConstraint('file_id', name='drive_storage_tiers_file_id_key')
    )
    op.create_index('ix_drive_storage_tiers_file_id', 'drive_storage_tiers', ['file_id'], unique=False, if_not_exists=True)
    op.create_table('auto_backup_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schedule_cron', sa.VARCHAR(length=100), server_default=sa.text("'''0 2 * * *'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=50), server_default=sa.text("'''minio_backup'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('retention_count', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_run_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_run_files', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='auto_backup_rules_created_by_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['drive_folders.id'], name='auto_backup_rules_folder_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='auto_backup_rules_pkey')
    )
    op.create_index('ix_auto_backup_rules_folder_id', 'auto_backup_rules', ['folder_id'], unique=False, if_not_exists=True)
    op.create_table('drive_user_sequences',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_sequence', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='drive_user_sequences_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name='drive_user_sequences_pkey')
    )
    op.create_table('drive_user_behaviors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('avg_daily_uploads', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_daily_downloads', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_daily_shares', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_daily_deletes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('typical_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('typical_ip_hashes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('upload_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('download_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('delete_threshold', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('alert_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_alert_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='drive_user_behaviors_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_user_behaviors_pkey'),
    sa.UniqueConstraint('user_id', name='drive_user_behaviors_user_id_key')
    )
    op.create_table('drive_change_feed',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('entity_name', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('parent_folder_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sequence_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['drive_files.id'], name='drive_change_feed_file_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['drive_folders.id'], name='drive_change_feed_folder_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='drive_change_feed_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_change_feed_pkey')
    )
    op.create_index('ix_drive_change_feed_user_id', 'drive_change_feed', ['user_id'], unique=False, if_not_exists=True)
    op.create_index('ix_drive_change_feed_sequence_id', 'drive_change_feed', ['sequence_id'], unique=False, if_not_exists=True)
    op.create_index('ix_drive_change_feed_occurred_at', 'drive_change_feed', ['occurred_at'], unique=False, if_not_exists=True)
    op.create_table('drive_guest_users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('share_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('invited_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name='drive_guest_users_invited_by_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_id'], ['file_shares.id'], name='drive_guest_users_share_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='drive_guest_users_pkey')
    )
    op.create_index('ix_drive_guest_users_share_id', 'drive_guest_users', ['share_id'], unique=False, if_not_exists=True)
    op.create_index('ix_drive_guest_users_email', 'drive_guest_users', ['email'], unique=False, if_not_exists=True)
    op.drop_index(op.f('ix_note_database_views_database_id'), table_name='note_database_views')
    op.drop_table('note_database_views')
    op.drop_index(op.f('ix_note_database_rows_database_id'), table_name='note_database_rows')
    op.drop_table('note_database_rows')
    op.drop_index(op.f('ix_note_database_properties_database_id'), table_name='note_database_properties')
    op.drop_table('note_database_properties')
    op.drop_index(op.f('ix_note_share_links_token'), table_name='note_share_links')
    op.drop_index(op.f('ix_note_share_links_note_id'), table_name='note_share_links')
    op.drop_table('note_share_links')
    op.drop_index(op.f('ix_note_databases_page_id'), table_name='note_databases')
    op.drop_index(op.f('ix_note_databases_owner_id'), table_name='note_databases')
    op.drop_index(op.f('ix_note_databases_notebook_id'), table_name='note_databases')
    op.drop_table('note_databases')
    op.drop_index(op.f('ix_form_response_approvals_response_id'), table_name='form_response_approvals')
    op.drop_table('form_response_approvals')
    op.drop_index(op.f('ix_form_quiz_results_form_id'), table_name='form_quiz_results')
    op.drop_table('form_quiz_results')
    op.drop_index(op.f('ix_form_consent_records_form_id'), table_name='form_consent_records')
    op.drop_table('form_consent_records')
    op.drop_index(op.f('ix_form_translations_form_id'), table_name='form_translations')
    op.drop_table('form_translations')
    op.drop_index(op.f('ix_form_schedules_form_id'), table_name='form_schedules')
    op.drop_table('form_schedules')
    op.drop_index(op.f('ix_form_response_drafts_form_id'), table_name='form_response_drafts')
    op.drop_table('form_response_drafts')
    op.drop_table('form_consents')
    op.drop_index(op.f('ix_form_automations_form_id'), table_name='form_automations')
    op.drop_table('form_automations')
    op.drop_table('form_approval_workflows')
    op.drop_index(op.f('ix_smart_folders_owner_id'), table_name='smart_folders')
    op.drop_table('smart_folders')
    op.drop_index(op.f('ix_calendar_webhooks_user_id'), table_name='calendar_webhooks')
    op.drop_table('calendar_webhooks')
    op.drop_index(op.f('ix_calendar_api_keys_user_id'), table_name='calendar_api_keys')
    op.drop_table('calendar_api_keys')
    # ### end Alembic commands ###
