"""add_is_external_to_users

Revision ID: 35f2a7a3c58d
Revises: proj1a2b3c4d5e
Create Date: 2026-03-13 14:24:35.688742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35f2a7a3c58d'
down_revision: Union[str, None] = 'proj1a2b3c4d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_external', sa.Boolean(), server_default='false', nullable=False, comment='External users (vendors, clients, partners) — not subject to domain restriction'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_external')
    # ### end Alembic commands ###
