"""phase2_notes_sharing_calendar_recurrence_file_share_activity

Revision ID: 598456d10bbe
Revises: 334f9af6510a
Create Date: 2026-03-10 17:11:24.713316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '598456d10bbe'
down_revision: Union[str, None] = '334f9af6510a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_feed',
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_shares',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('share_link', sa.String(length=200), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['drive_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_link')
    )
    op.add_column('calendar_events', sa.Column('recurrence_rule', sa.String(length=500), nullable=True, comment='iCal RRULE string, e.g. FREQ=WEEKLY;BYDAY=MO,WE,FR'))
    op.add_column('calendar_events', sa.Column('recurrence_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('calendar_events', sa.Column('parent_event_id', sa.UUID(), nullable=True, comment='FK to parent event for recurring series instances'))
    op.create_foreign_key(None, 'calendar_events', 'calendar_events', ['parent_event_id'], ['id'], ondelete='CASCADE')
    op.add_column('notes', sa.Column('shared_with', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='JSON array of user-id strings this note is shared with'))
    op.add_column('notes', sa.Column('is_shared', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_shared')
    op.drop_column('notes', 'shared_with')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'parent_event_id')
    op.drop_column('calendar_events', 'recurrence_end')
    op.drop_column('calendar_events', 'recurrence_rule')
    op.drop_table('file_shares')
    op.drop_table('activity_feed')
    # ### end Alembic commands ###
