"""add_source_module_to_calendar_events

Revision ID: 842a2ead8709
Revises: c809ea041d9a
Create Date: 2026-03-13 13:23:25.529980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842a2ead8709'
down_revision: Union[str, None] = 'c809ea041d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('source_module', sa.String(length=50), nullable=True, comment='ERP module that created this event: hr, crm, projects, finance, meetings, etc.'))
    op.add_column('calendar_events', sa.Column('source_id', sa.String(length=255), nullable=True, comment='ID of the source object in the originating module (task_id, leave_id, etc.)'))
    op.create_index(op.f('ix_calendar_events_source_module'), 'calendar_events', ['source_module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_source_module'), table_name='calendar_events')
    op.drop_column('calendar_events', 'source_id')
    op.drop_column('calendar_events', 'source_module')
    # ### end Alembic commands ###
